on: 
  pull_request:
    types:
      - opened
    branches: master

jobs:
  build_ig:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Publisher
        run: ./_updatePublisher.sh -f -y
      - name: Install Jekyll
        run: gem install jekyll
      - name: Build IG
        run: ./_genonce.sh
