on: 
  pull_request:
    types: [opened, edited, reopened]
    branches: master

jobs:
  build_ig:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Install Publisher
      #   run: ./_updatePublisher.sh -f -y
      # - name: Install Jekyll
      #   run: gem install jekyll
      # - name: Build IG
      #   run: ./_genonce.sh
      - name: Install Tooling Jar
        run: ./_updateCQFTooling.sh -f
      - name: Refresh Test Data
        run: ./_refreshTestData.sh
  start_ruler:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
      ruler:
        image: cschuler72/cqf-ruler
    steps:
      - name: Install Publisher
        run: ./_updatePublisher.sh -f -y
      - name: Install Tooling Jar
        run: ./_updateCQFTooling.sh -f
