on: 
  pull_request:
    types: [opened, edited, reopened]
    branches: master

jobs:
  start_service_build_ig_test:
    needs: build_ig
    runs-on: macos-13
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
      ruler:
        image: cschuler72/cqf-ruler
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Install Publisher
      #   run: ./_updatePublisher.sh -f -y
      # - name: Install Jekyll
      #   run: gem install jekyll
      # - name: Build IG
      #   run: ./_genonce.sh
      - name: Install Tooling Jar
        run: ./_updateCQFTooling.sh -f
      # - name: Refresh Test Data
      #   run: ./_refreshTestData.sh
      - name: Refresh Bundles
        run: ./_refresh.sh
      - name: Output Rec01 Bundle
        run: cat ./bundles/plandefinition/opioidcds-01/opioidcds-01-bundle.json 
