on: 
  pull_request:
    types: [opened, edited, reopened]
    branches: master

jobs:
  build_ig:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Install Publisher
      #   run: ./_updatePublisher.sh -f -y
      # - name: Install Jekyll
      #   run: gem install jekyll
      # - name: Build IG
      #   run: ./_genonce.sh
      - name: Install Tooling Jar
        shell: bash-wrapper {0}
        run: bash ./_updateCQFTooling.sh -f
      - name: Refresh Test Data
        run: ./_refreshTestData.sh
