on: 
  pull_request:
    types: [opened, edited, reopened]
    branches: master

jobs:
  start_service_build_ig_test:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
      ruler:
        image: cschuler72/cqf-ruler
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      # - name: Install Publisher
      #   run: ./_updatePublisher.sh -f -y
      # - name: Install Jekyll
      #   run: gem install jekyll
      # - name: Build IG
      #   run: ./_genonce.sh
      - name: Install Tooling Jar
        run: ./_updateCQFTooling.sh -f
      # - name: Refresh Test Data
      #   run: ./_refreshTestData.sh
      - name: Refresh Bundles
        run: ./_refresh.sh
      - name: Load Rec01 Bundle
        run: curl --location --request POST '127.0.0.1:8080/fhir' --header 'Content-Type: application/json' --data-binary @./bundles/plandefinition/opioidcds-01/opioidcds-01-bundle.json 
